SLOPE_X_DEG = 0.0
SLOPE_Y_DEG = 0.0
BASE_WAVELENGTH = 15.0
OCTAVES = 5
PERSISTENCE = 0.3
LACUNARITY = 2.0
ROUGHNESS_AMPLITUDE = 0.5

PROJECTION_PATH_CENTRE = [0, 0]
PROJECTION_PATH_WIDTH = 20
PROJECTION_PATH_HEIGHT = 20
PROJECTION_PATH_ORIENTATION = 45
PROJECTION_PATH_INCREMENT = 0.1

POSE = [0, 0, 0, 0, 0, 0]