import numpy as np

SLOPE_X_DEG = 0.0
SLOPE_Y_DEG = 0.0
BASE_WAVELENGTH = 15.0
OCTAVES = 5
PERSISTENCE = 0.3
LACUNARITY = 2.0
ROUGHNESS_AMPLITUDE = 0.5

PROJECTION_PATH_CENTRE = [0, 0]
PROJECTION_PATH_WIDTH = 20
PROJECTION_PATH_HEIGHT = 20
PROJECTION_PATH_ORIENTATION = 45
PROJECTION_PATH_INCREMENT = 0.1

POSE = [0, 0, 0, 0, 0, 0]

PATH_CENTRE = [0, -np.pi/4]
PATH_WIDTH = 0.9 * np.pi / 2
PATH_HEIGHT = 0.9 * np.pi/2
PATH_THETA_PERIOD = 2.0
PATH_PHI_PERIOD = 1.1
PATH_PHASE_OFFSET = np.pi / 2
PATH_NUM_POINTS = 10000
PATH_DURATION = 10.0